# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AlphabeticKeyBoard.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from functools import partial
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.line_edit = ""
        self.type_mode = ""
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1023, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 961, 541))
        self.label.setStyleSheet("background-image: url(Images/sunset.jpg);\n"
"border-radius:30px;\n"
"border: 2px solid black;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(39, 19, 941, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(20, 110, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background: none;\n"
"border: 1px solid black;\n"
"border-radius: 12px;")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 110, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background: none;\n"
"border: 1px solid black;\n"
"border-radius: 12px;")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(710, 110, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background: none;\n"
"border: 1px solid black;\n"
"border-radius: 12px;")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(200, 30, 561, 41))
        self.label_2.setStyleSheet("border: 1px solid #ffaa00;\n"
"border-radius: 12px;\n"
"background: none;\n"
"background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(420, 110, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background: none;\n"
"border: 1px solid black;\n"
"border-radius: 12px;")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(170, 210, 611, 291))
        self.frame_2.setStyleSheet("border: 2px solid;\n"
"border-color: rgba(159, 159, 159, 255);\n"
"border-radius: 20px;\n"
"background-color: rgba(207,211,216,255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(550, 10, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("#pushButton_4{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-right-radius: 20px;\n"
"}\n"
"#pushButton_4:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_4:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(470, 220, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton {\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgba(170,175,185,255);\n"
"border-radius:5px;\n"
"border-bottom-right-radius: 20px;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"background-color: rgb(153,156,156);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 10, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-left-radius: 20px;\n"
"\n"
"}\n"
"#pushButton_2:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_2:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(70, 10, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"}\n"
"#pushButton_3:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_3:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(130, 10, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("#pushButton_5{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_5:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_5:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(190, 10, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("#pushButton_6{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_6:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_6:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_7.setGeometry(QtCore.QRect(250, 10, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("#pushButton_7{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_7:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"\n"
"#pushButton_7:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_8.setGeometry(QtCore.QRect(310, 10, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("#pushButton_8{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_8:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_8:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_9.setGeometry(QtCore.QRect(370, 10, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("#pushButton_9{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_9:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_9:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_10.setGeometry(QtCore.QRect(430, 10, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("#pushButton_10{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_10:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_10:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_11.setGeometry(QtCore.QRect(490, 10, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("#pushButton_11{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_11:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_11:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_12.setGeometry(QtCore.QRect(40, 80, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("#pushButton_12{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_12:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_12:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_13.setGeometry(QtCore.QRect(100, 80, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("#pushButton_13{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_13:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_13:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_14.setGeometry(QtCore.QRect(160, 80, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("#pushButton_14{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_14:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_14:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_15.setGeometry(QtCore.QRect(220, 80, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("#pushButton_15{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_15:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_15:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_16.setGeometry(QtCore.QRect(280, 80, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("#pushButton_16{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_16:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_16:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_17.setGeometry(QtCore.QRect(340, 80, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("#pushButton_17{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_17:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_17:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_18.setGeometry(QtCore.QRect(400, 80, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("#pushButton_18{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_18:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_18:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_19.setGeometry(QtCore.QRect(460, 80, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("#pushButton_19{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_19:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_19:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_20.setGeometry(QtCore.QRect(520, 80, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("#pushButton_20{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_20:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_20:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_21.setGeometry(QtCore.QRect(10, 150, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setStyleSheet("#pushButton_21{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgba(171,176,188,255);\n"
"border-radius: 5px;\n"
"\n"
"\n"
"}\n"
"\n"
"#pushButton_21:hover{\n"
"background-color: rgb(153,156,156);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_21:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_22.setGeometry(QtCore.QRect(100, 150, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet("#pushButton_22{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_22:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_22:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_23.setGeometry(QtCore.QRect(220, 150, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("#pushButton_23{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_23:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_23:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_24.setGeometry(QtCore.QRect(160, 150, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setStyleSheet("#pushButton_24{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_24:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_24:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_25.setGeometry(QtCore.QRect(280, 150, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setStyleSheet("#pushButton_25{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_25:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_25:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_26.setGeometry(QtCore.QRect(340, 150, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setStyleSheet("#pushButton_26{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_26:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_26:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_27.setGeometry(QtCore.QRect(400, 150, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setStyleSheet("#pushButton_27{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_27:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_27:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_28.setGeometry(QtCore.QRect(460, 150, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setStyleSheet("#pushButton_28{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_28:hover{\n"
"background-color: rgb(200,207,215);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_28:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_29.setGeometry(QtCore.QRect(530, 150, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setStyleSheet("#pushButton_29{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color:  rgba(171,176,188,255);\n"
"border-radius: 5px;\n"
"}\n"
"#pushButton_29:hover{\n"
"background-color: rgb(153,156,156);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"\n"
"#pushButton_29:pressed {\n"
"padding-bottom: 10px;\n"
"padding-right: 10px;\n"
"background-color:rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_30.setGeometry(QtCore.QRect(10, 220, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setStyleSheet("#pushButton_30{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgba(171,176,188,255);\n"
"border-radius: 5px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"\n"
"}\n"
"\n"
"#pushButton_30:hover{\n"
"background-color: rgb(153,156,156);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_30:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color: rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_31.setGeometry(QtCore.QRect(160, 220, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(29)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setStyleSheet("#pushButton_31{\n"
"border: 2px solid;\n"
"border-left-color: none;\n"
"border-right-color: none;\n"
"border-top-color:  none;\n"
"border-bottom-color: rgb(157, 157, 157);\n"
"background-color: rgba(171,176,188,255);\n"
"border-radius: 5px;\n"
"\n"
"}\n"
"\n"
"#pushButton_31:hover{\n"
"background-color: rgb(153,156,156);\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"#pushButton_31:pressed {\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"background-color:rgba(171,176,188,255);\n"
"}\n"
"\n"
"")
        self.pushButton_31.setText("")
        self.pushButton_31.setObjectName("pushButton_31")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "User ID"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Mobile No. +91"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; text-decoration: underline;\">Alphabetic KeyBoard</span></p></body></html>"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Email ID"))
        self.pushButton.setText(_translate("MainWindow", "return"))
        self.pushButton_21.setText(_translate("MainWindow", "⌂"))
        self.pushButton_29.setText(_translate("MainWindow", "←"))
        self.pushButton_30.setText(_translate("MainWindow", "123"))
        
        # self.pushButton_2.setText(_translate("MainWindow", "q"))
        # self.pushButton_3.setText(_translate("MainWindow", "w"))
        # self.pushButton_5.setText(_translate("MainWindow", "e"))
        # self.pushButton_6.setText(_translate("MainWindow", "r"))
        # self.pushButton_7.setText(_translate("MainWindow", "t"))
        # self.pushButton_8.setText(_translate("MainWindow", "y"))
        # self.pushButton_9.setText(_translate("MainWindow", "u"))
        # self.pushButton_10.setText(_translate("MainWindow", "i"))
        # self.pushButton_11.setText(_translate("MainWindow", "o"))
        # self.pushButton_4.setText(_translate("MainWindow", "p"))
        # self.pushButton_12.setText(_translate("MainWindow", "a")) 
        # self.pushButton_13.setText(_translate("MainWindow", "s"))
        # self.pushButton_14.setText(_translate("MainWindow", "d"))
        # self.pushButton_15.setText(_translate("MainWindow", "f")) 
        # self.pushButton_16.setText(_translate("MainWindow", "g"))
        # self.pushButton_17.setText(_translate("MainWindow", "h"))
        # self.pushButton_18.setText(_translate("MainWindow", "j"))
        # self.pushButton_19.setText(_translate("MainWindow", "k")) 
        # self.pushButton_20.setText(_translate("MainWindow", "l"))
        # self.pushButton_22.setText(_translate("MainWindow", "z"))
        # self.pushButton_23.setText(_translate("MainWindow", "x"))
        # self.pushButton_24.setText(_translate("MainWindow", "c"))
        # self.pushButton_25.setText(_translate("MainWindow", "v"))
        # self.pushButton_26.setText(_translate("MainWindow", "b"))
        # self.pushButton_27.setText(_translate("MainWindow", "n")) 
        # self.pushButton_28.setText(_translate("MainWindow", "m"))
        self.pushButton.clicked.connect(self.frame_2.close)
        self.frame_2.hide()
        self.frame.mousePressEvent = lambda event: self.frame_2.hide()
        self.small_latter()
        self.on_button_clicked()
        self.pushButton_30.clicked.connect(self.special_char)
        self.pushButton_21.clicked.connect(self.capital_latter)
        
        # self.pushButton_21.clicked.connect(self.small_latter('capital'))
        self.pushButton_29.clicked.connect(lambda: self.delete_character(self.line_edit))
        self.lineEdit.mousePressEvent = lambda event: self.show_keyboard(self.lineEdit)
        self.lineEdit_2.mousePressEvent = lambda event: self.show_keyboard(self.lineEdit_2)
        self.lineEdit_3.mousePressEvent = lambda event: self.show_keyboard(self.lineEdit_3)
        self.lineEdit_4.mousePressEvent = lambda event: self.show_keyboard(self.lineEdit_4)
    def delete_character(self, lineEdit):
        print(lineEdit, "delete")
        cursor_position = lineEdit.cursorPosition() 
        if lineEdit is None:
             print("Invalid line edit type")
             return
        if cursor_position != 0:
                lineEdit.setText(lineEdit.text()[:cursor_position - 1] + lineEdit.text()[cursor_position:])
                lineEdit.setCursorPosition(cursor_position - 1)
        else:
                print("Cursor index is 0")

    def on_button_clicked(self):
        print(self.type_mode, ": in button check the mode")
         
        if (self.type_mode == 'numeric'):
                
                self.pushButton_2.clicked.connect(lambda _, value = str("1"): self.set_value_to_lineEdit(self.line_edit, value))
                self.pushButton_3.clicked.connect(lambda _, value = str("2"): self.set_value_to_lineEdit(self.line_edit, value)) 
                self.pushButton_5.clicked.connect(lambda _, value = str("3"): self.set_value_to_lineEdit(self.line_edit, value))
                self.pushButton_6.clicked.connect(lambda _, value = str(self.pushButton_6.text()): self.set_value_to_lineEdit(self.line_edit, value))
                self.pushButton_7.clicked.connect(lambda _, value = str(self.pushButton_7.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
                self.pushButton_8.clicked.connect(lambda _, value = str(self.pushButton_8.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_9.clicked.connect(lambda _, value = str(self.pushButton_9.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_10.clicked.connect(lambda _, value = str(self.pushButton_10.text()): self.set_value_to_lineEdit(self.line_edit, value))
        #         # self.pushButton_11.clicked.connect(lambda _, value = str(self.pushButton_11.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_4.clicked.connect(lambda _, value = str(self.pushButton_4.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_12.clicked.connect(lambda _, value = str(self.pushButton_12.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_13.clicked.connect(lambda _, value = str(self.pushButton_13.text()): self.set_value_to_lineEdit(self.line_edit, value))
        #         # self.pushButton_14.clicked.connect(lambda _, value = str(self.pushButton_14.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_15.clicked.connect(lambda _, value = str(self.pushButton_15.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_16.clicked.connect(lambda _, value = str(self.pushButton_16.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_17.clicked.connect(lambda _, value = str(self.pushButton_17.text()): self.set_value_to_lineEdit(self.line_edit, value))
        #         # self.pushButton_18.clicked.connect(lambda _, value = str(self.pushButton_18.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_19.clicked.connect(lambda _, value = str(self.pushButton_19.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_20.clicked.connect(lambda _, value = str(self.pushButton_20.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_22.clicked.connect(lambda _, value = str(self.pushButton_22.text()): self.set_value_to_lineEdit(self.line_edit, value))
        #         # self.pushButton_23.clicked.connect(lambda _, value = str(self.pushButton_23.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_24.clicked.connect(lambda _, value = str(self.pushButton_24.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_25.clicked.connect(lambda _, value = str(self.pushButton_25.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_26.clicked.connect(lambda _, value = str(self.pushButton_26.text()): self.set_value_to_lineEdit(self.line_edit, value))
        #         # self.pushButton_27.clicked.connect(lambda _, value = str(self.pushButton_27.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_28.clicked.connect(lambda _, value = str(self.pushButton_28.text()): self.set_value_to_lineEdit(self.line_edit, value))
        elif( self.type_mode == 'capital'):
                print("elif of capital")
                self.pushButton_2.clicked.connect(lambda _, value = str("Q"): self.set_value_to_lineEdit(self.line_edit, value))
                self.pushButton_3.clicked.connect(lambda _, value = str("W"): self.set_value_to_lineEdit(self.line_edit, value)) 
                self.pushButton_5.clicked.connect(lambda _, value = str("E"): self.set_value_to_lineEdit(self.line_edit, value))
                self.pushButton_6.clicked.connect(lambda _, value = str(self.pushButton_6.text()): self.set_value_to_lineEdit(self.line_edit, value))
                self.pushButton_7.clicked.connect(lambda _, value = str(self.pushButton_7.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
                self.pushButton_8.clicked.connect(lambda _, value = str(self.pushButton_8.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_9.clicked.connect(lambda _, value = str(self.pushButton_9.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_10.clicked.connect(lambda _, value = str(self.pushButton_10.text()): self.set_value_to_lineEdit(self.line_edit, value))
        #         # self.pushButton_11.clicked.connect(lambda _, value = str(self.pushButton_11.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_4.clicked.connect(lambda _, value = str(self.pushButton_4.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_12.clicked.connect(lambda _, value = str(self.pushButton_12.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_13.clicked.connect(lambda _, value = str(self.pushButton_13.text()): self.set_value_to_lineEdit(self.line_edit, value))
        #         # self.pushButton_14.clicked.connect(lambda _, value = str(self.pushButton_14.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_15.clicked.connect(lambda _, value = str(self.pushButton_15.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_16.clicked.connect(lambda _, value = str(self.pushButton_16.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_17.clicked.connect(lambda _, value = str(self.pushButton_17.text()): self.set_value_to_lineEdit(self.line_edit, value))
        #         # self.pushButton_18.clicked.connect(lambda _, value = str(self.pushButton_18.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_19.clicked.connect(lambda _, value = str(self.pushButton_19.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_20.clicked.connect(lambda _, value = str(self.pushButton_20.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_22.clicked.connect(lambda _, value = str(self.pushButton_22.text()): self.set_value_to_lineEdit(self.line_edit, value))
        #         # self.pushButton_23.clicked.connect(lambda _, value = str(self.pushButton_23.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_24.clicked.connect(lambda _, value = str(self.pushButton_24.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_25.clicked.connect(lambda _, value = str(self.pushButton_25.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        #         # self.pushButton_26.clicked.connect(lambda _, value = str(self.pushButton_26.text()): self.set_value_to_lineEdit(self.line_edit, value))
        #         # self.pushButton_27.clicked.connect(lambda _, value = str(self.pushButton_27.text()): self.set_value_to_lineEdit(self.line_edit, value)) 
        
        #         # self.pushButton_28.clicked.connect(lambda _, value = str(self.pushButton_28.text()): self.set_value_to_lineEdit(self.line_edit, value))
        elif( self.type_mode == 'small'):
                self.pushButton_2.clicked.connect(lambda _, value = str("q"): self.set_value_to_lineEdit(self.line_edit, value))
                self.pushButton_3.clicked.connect(lambda _, value = str("w"): self.set_value_to_lineEdit(self.line_edit, value)) 
                self.pushButton_5.clicked.connect(lambda _, value = str("e"): self.set_value_to_lineEdit(self.line_edit, value))        
        else:
             print("mode not valide")    
        # for button in self.buttons():
        #         button.clicked.connect(lambda _, value = str(button.text()): self.set_value_to_lineEdit(self.line_edit, value))
        #         print("button value :" + str(button.text()))
                # button.clicked.connect(functools.partial(self.set_value_to_lineEdit, self.line_edit, button.text()))
    def set_value_to_lineEdit(self, lineEdit, value):
        print(value, ": value")
        
        if lineEdit is None:
             print("Invalid Line Edit")
             return
        # cursor_position = lineEdit.cursorPosition() 
        # print(cursor_position, "cursor")
        # lineEdit.setText(str(lineEdit.text()[:cursor_position]) + str(value) + str(lineEdit.text()[cursor_position:])) 
        # lineEdit.setCursorPosition(cursor_position + 1)
        lineEdit.setText(str(lineEdit.text()) + str(value))
        
        
    def show_keyboard(self, line_num):
        self.line_edit = line_num
        # print(line_num, ": line Edit Number")
        
        self.frame_2.show()
        
    def small_latter(self):
        
        self.type_mode = 'small'
        # Define lowercase letters
        lowercase_letters = "qwertyuiopasdfghjklzxcvbnm"
        # Iterate through buttons and assign lowercase letters
        for i, button in enumerate(self.buttons()):
            button.setText(lowercase_letters[i])
        
        
        
        
    def special_char(self):
        
        self.type_mode = "numeric"
        print(self.type_mode, ": in special check the mode")
        # Define Special letters
        special_characters = "1234567890-/:;()*$@.,!#%+="
        # Iterate through buttons and assign Special letters
        for i, button in enumerate(self.buttons()):
            button.setText(special_characters[i])
        #     print(button.text(), "after setting the special char")
        # self.pushButton_30.clicked.connect(self.small_latter)
        
    def capital_latter(self):
        self.type_mode = "capital"
        print(self.type_mode, ": in capital check the mode")
        # Define uppercase letters
        uppercase_letters = "QWERTYUIOPASDFGHJKLZXCVBNM"
        # Iterate through buttons and assign uppercase letters
        for i, button in enumerate(self.buttons()):
            button.setText(uppercase_letters[i])
             
        
        # self.pushButton_21.clicked.connect(self.small_latter)
        
        
             
    def buttons(self):
        # Return the list of buttons for assigning the letters
        return [
            self.pushButton_2, self.pushButton_3, self.pushButton_5, self.pushButton_6,
            self.pushButton_7, self.pushButton_8, self.pushButton_9, self.pushButton_10,
            self.pushButton_11, self.pushButton_4, self.pushButton_12, self.pushButton_13,
            self.pushButton_14, self.pushButton_15, self.pushButton_16, self.pushButton_17,
            self.pushButton_18, self.pushButton_19, self.pushButton_20, self.pushButton_22,
            self.pushButton_23, self.pushButton_24, self.pushButton_25, self.pushButton_26,
            self.pushButton_27, self.pushButton_28
        ]
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
